# GitHub Dependency Review Action
# Scans the pull requests for dependency changes and will raise an error if any vulnerabilities or invalid licenses are being introduced.
# Repo: https://github.com/actions/dependency-review-action

name: "Dependency Review"
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          show-patched-versions: true
          retry-on-snapshot-warnings: true
